[package]
name = "bitwig-monome"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
monome-rs = "1.1.3"
rosc = "0.7.0"
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.2"
